version: "3.0"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  
  backend:
    build: ./backend
    command: npm run start:prod
    ports:
      - 3000:3000
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: password
      MONGO_DATABASE: easygen
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      AUTH_SECRET_KEY: your_secret_key
      AUTH_EXPIRATION_TIME: 10m
      AUTH_REFRESH_TOKEN_DURATION: 4w
      API_VERSION: v1
    restart: always

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      VITE_API_BASE_URL: http://backend:3000/api/v1
    restart: always

volumes:
  db:
